### ISSUE TITLE
Cannot save 

### ISSUE THREAD

**Issue by msolomianiuk** [the-via/app#176]
- was able to save the same layout before
 - tried both chrome and edge
 
here is the screenshot of the error page:
![image](https://github.com/the-via/app/assets/11045460/dfc5738a-65ea-40da-a896-faf81dfd8c6c)

and here is the VIA-app-errors.csv:
```
timestamp, productName, vendorId, productId, message
20:32:47.390, Keychron Q2, 0x3434, 0x0111, "Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 0 0 0
Response: 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
20:32:47.403, Keychron Q2, 0x3434, 0x0111, "Error: Receiving incorrect response for command
    at KeyboardAPI._hidCommand (https://usevia.app/assets/index-f59e2e2a.js:3:9407)
    at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-f59e2e2a.js:3:8661)"
20:32:47.410, Keychron Q2, 0x3434, 0x0111, "Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 0 0 1
Response: 255 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
20:32:47.413, Keychron Q2, 0x3434, 0x0111, "Error: Receiving incorrect response for command
    at KeyboardAPI._hidCommand (https://usevia.app/assets/index-f59e2e2a.js:3:9407)
    at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-f59e2e2a.js:3:8661)"
20:32:47.419, Keychron Q2, 0x3434, 0x0111, "Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 1 0 0
Response: 255 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
20:32:47.422, Keychron Q2, 0x3434, 0x0111, "Error: Receiving incorrect response for command
    at KeyboardAPI._hidCommand (https://usevia.app/assets/index-f59e2e2a.js:3:9407)
    at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-f59e2e2a.js:3:8661)"
20:32:47.427, Keychron Q2, 0x3434, 0x0111, "Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 1 0 1
Response: 255 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
20:32:47.431, Keychron Q2, 0x3434, 0x0111, "Error: Receiving incorrect response for command
    at KeyboardAPI._hidCommand (https://usevia.app/assets/index-f59e2e2a.js:3:9407)
    at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-f59e2e2a.js:3:8661)"
20:32:47.436, Keychron Q2, 0x3434, 0x0111, "Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 2 0 0
Response: 255 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
20:32:47.439, Keychron Q2, 0x3434, 0x0111, "Error: Receiving incorrect response for command
    at KeyboardAPI._hidCommand (https://usevia.app/assets/index-f59e2e2a.js:3:9407)
    at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-f59e2e2a.js:3:8661)"
20:32:47.444, Keychron Q2, 0x3434, 0x0111, "Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 2 0 1
Response: 255 2 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
20:32:47.448, Keychron Q2, 0x3434, 0x0111, "Error: Receiving incorrect response for command
    at KeyboardAPI._hidCommand (https://usevia.app/assets/index-f59e2e2a.js:3:9407)
    at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-f59e2e2a.js:3:8661)"
20:32:47.453, Keychron Q2, 0x3434, 0x0111, "Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 3 0 0
Response: 255 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
20:32:47.456, Keychron Q2, 0x3434, 0x0111, "Error: Receiving incorrect response for command
    at KeyboardAPI._hidCommand (https://usevia.app/assets/index-f59e2e2a.js:3:9407)
    at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-f59e2e2a.js:3:8661)"
20:32:47.462, Keychron Q2, 0x3434, 0x0111, "Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 3 0 1
Response: 255 3 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
20:32:47.465, Keychron Q2, 0x3434, 0x0111, "Error: Receiving incorrect response for command
    at KeyboardAPI._hidCommand (https://usevia.app/assets/index-f59e2e2a.js:3:9407)
    at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-f59e2e2a.js:3:8661)"
20:32:47.470, Keychron Q2, 0x3434, 0x0111, "Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 4 0 0
Response: 255 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
20:32:47.473, Keychron Q2, 0x3434, 0x0111, "Error: Receiving incorrect response for command
    at KeyboardAPI._hidCommand (https://usevia.app/assets/index-f59e2e2a.js:3:9407)
    at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-f59e2e2a.js:3:8661)"
20:32:47.478, Keychron Q2, 0x3434, 0x0111, "Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 4 0 1
Response: 255 4 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
20:32:47.480, Keychron Q2, 0x3434, 0x0111, "Error: Receiving incorrect response for command
    at KeyboardAPI._hidCommand (https://usevia.app/assets/index-f59e2e2a.js:3:9407)
    at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-f59e2e2a.js:3:8661)"
```

**Comment by ArvindRSingh** [comment]
Facing the same issue, was never able to save.
