### ISSUE TITLE
DZ60 - error in logs on backlight

### ISSUE THREAD

**Issue by Xhelliom** [the-via/app#197]
Hello :) 

i have currently an issue on the log on via : 
```
14:01:57.659
  Command Name: BACKLIGHT_CONFIG_GET_VALUE
  Command: 8 9
  Response: 255 9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  Device: DZ60
  Vid: 0x445A
  Pid: 0x2260

14:01:57.687
  Error: Receiving incorrect response for command
  at KeyboardAPI._hidCommand (https://usevia.app/assets/index-a1faf99e.js:3:9407)
  at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-a1faf99e.js:3:8661)
  Device: DZ60
  Vid: 0x445A
  Pid: 0x2260

14:01:57.697
  Loading lighting/menu data failed
  Device: DZ60
  Vid: 0x445A
  Pid: 0x2260
```

And i think the menu to configure lighting effect is not there, do you have any infos ?

Thanks

**Comment by Xhelliom** [comment]
So; i did reflash the dz60_rev2 and now its ok.

For more informations, the default tofu redux kit pcb throw those errors.
