### ISSUE TITLE
[Bug] Saving my configuration is not possible

### ISSUE THREAD

**Issue by Birne94** [the-via/app#76]
I am using the application on usevia.app and after making changes to my configuration (Keychron Q3 and using an Apple Macbook with M1 chip), I am unable to save using the `Save and Load` page. Clicking the `Save` button gives the following errors in the console and nothing else happens:
```
react_devtools_backend.js:4012 Command for c1eb1f72-1663-4c56-8c61-5298515477ca: (5) [0, 20, 0, 0, 0] Bad Resp: Uint8Array(32) [255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']
overrideMethod @ react_devtools_backend.js:4012
_hidCommand @ index.fcb52d768a746885a155.js:2
await in _hidCommand (async)
flushQueue @ index.fcb52d768a746885a155.js:2
(anonymous) @ index.fcb52d768a746885a155.js:2
hidCommand @ index.fcb52d768a746885a155.js:2
getEncoderValue @ index.fcb52d768a746885a155.js:2
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
onClick @ index.fcb52d768a746885a155.js:719
Ie @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
We @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Vr @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Ar @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
fs @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Fe @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
$r @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Xn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
qn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
index.fcb52d768a746885a155.js:2 Uncaught (in promise) Error: Receiving incorrect response for command
    at Sn._hidCommand (index.fcb52d768a746885a155.js:2:54957)
    at async Sn.flushQueue (index.fcb52d768a746885a155.js:2:54348)
_hidCommand @ index.fcb52d768a746885a155.js:2
await in _hidCommand (async)
Ie @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
We @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Vr @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Ar @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
fs @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Fe @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
$r @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Xn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
qn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
react_devtools_backend.js:4012 Command for c1eb1f72-1663-4c56-8c61-5298515477ca: (5) [0, 20, 0, 0, 1] Bad Resp: Uint8Array(32) [255, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']
overrideMethod @ react_devtools_backend.js:4012
_hidCommand @ index.fcb52d768a746885a155.js:2
await in _hidCommand (async)
flushQueue @ index.fcb52d768a746885a155.js:2
await in flushQueue (async)
(anonymous) @ index.fcb52d768a746885a155.js:2
hidCommand @ index.fcb52d768a746885a155.js:2
getEncoderValue @ index.fcb52d768a746885a155.js:2
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
onClick @ index.fcb52d768a746885a155.js:719
Ie @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
We @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Vr @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Ar @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
fs @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Fe @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
$r @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Xn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
qn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
react_devtools_backend.js:4012 Command for c1eb1f72-1663-4c56-8c61-5298515477ca: (5) [0, 20, 1, 0, 0] Bad Resp: Uint8Array(32) [255, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']
overrideMethod @ react_devtools_backend.js:4012
_hidCommand @ index.fcb52d768a746885a155.js:2
await in _hidCommand (async)
flushQueue @ index.fcb52d768a746885a155.js:2
await in flushQueue (async)
(anonymous) @ index.fcb52d768a746885a155.js:2
hidCommand @ index.fcb52d768a746885a155.js:2
getEncoderValue @ index.fcb52d768a746885a155.js:2
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
onClick @ index.fcb52d768a746885a155.js:719
Ie @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
We @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Vr @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Ar @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
fs @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Fe @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
$r @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Xn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
qn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
react_devtools_backend.js:4012 Command for c1eb1f72-1663-4c56-8c61-5298515477ca: (5) [0, 20, 1, 0, 1] Bad Resp: Uint8Array(32) [255, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']
overrideMethod @ react_devtools_backend.js:4012
_hidCommand @ index.fcb52d768a746885a155.js:2
await in _hidCommand (async)
flushQueue @ index.fcb52d768a746885a155.js:2
await in flushQueue (async)
(anonymous) @ index.fcb52d768a746885a155.js:2
hidCommand @ index.fcb52d768a746885a155.js:2
getEncoderValue @ index.fcb52d768a746885a155.js:2
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
onClick @ index.fcb52d768a746885a155.js:719
Ie @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
We @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Vr @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Ar @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
fs @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Fe @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
$r @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Xn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
qn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
react_devtools_backend.js:4012 Command for c1eb1f72-1663-4c56-8c61-5298515477ca: (5) [0, 20, 2, 0, 0] Bad Resp: Uint8Array(32) [255, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']
overrideMethod @ react_devtools_backend.js:4012
_hidCommand @ index.fcb52d768a746885a155.js:2
await in _hidCommand (async)
flushQueue @ index.fcb52d768a746885a155.js:2
await in flushQueue (async)
(anonymous) @ index.fcb52d768a746885a155.js:2
hidCommand @ index.fcb52d768a746885a155.js:2
getEncoderValue @ index.fcb52d768a746885a155.js:2
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
onClick @ index.fcb52d768a746885a155.js:719
Ie @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
We @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Vr @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Ar @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
fs @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Fe @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
$r @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Xn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
qn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
react_devtools_backend.js:4012 Command for c1eb1f72-1663-4c56-8c61-5298515477ca: (5) [0, 20, 2, 0, 1] Bad Resp: Uint8Array(32) [255, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']
overrideMethod @ react_devtools_backend.js:4012
_hidCommand @ index.fcb52d768a746885a155.js:2
await in _hidCommand (async)
flushQueue @ index.fcb52d768a746885a155.js:2
await in flushQueue (async)
(anonymous) @ index.fcb52d768a746885a155.js:2
hidCommand @ index.fcb52d768a746885a155.js:2
getEncoderValue @ index.fcb52d768a746885a155.js:2
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
onClick @ index.fcb52d768a746885a155.js:719
Ie @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
We @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Vr @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Ar @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
fs @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Fe @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
$r @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Xn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
qn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
react_devtools_backend.js:4012 Command for c1eb1f72-1663-4c56-8c61-5298515477ca: (5) [0, 20, 3, 0, 0] Bad Resp: Uint8Array(32) [255, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']
overrideMethod @ react_devtools_backend.js:4012
_hidCommand @ index.fcb52d768a746885a155.js:2
await in _hidCommand (async)
flushQueue @ index.fcb52d768a746885a155.js:2
await in flushQueue (async)
(anonymous) @ index.fcb52d768a746885a155.js:2
hidCommand @ index.fcb52d768a746885a155.js:2
getEncoderValue @ index.fcb52d768a746885a155.js:2
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
onClick @ index.fcb52d768a746885a155.js:719
Ie @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
We @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Vr @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Ar @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
fs @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Fe @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
$r @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Xn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
qn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
react_devtools_backend.js:4012 Command for c1eb1f72-1663-4c56-8c61-5298515477ca: (5) [0, 20, 3, 0, 1] Bad Resp: Uint8Array(32) [255, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']
overrideMethod @ react_devtools_backend.js:4012
_hidCommand @ index.fcb52d768a746885a155.js:2
await in _hidCommand (async)
flushQueue @ index.fcb52d768a746885a155.js:2
await in flushQueue (async)
(anonymous) @ index.fcb52d768a746885a155.js:2
hidCommand @ index.fcb52d768a746885a155.js:2
getEncoderValue @ index.fcb52d768a746885a155.js:2
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
(anonymous) @ index.fcb52d768a746885a155.js:719
onClick @ index.fcb52d768a746885a155.js:719
Ie @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
We @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Vr @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Ar @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
(anonymous) @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
fs @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Fe @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
$r @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
Xn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
qn @ lib-index-56d6bcf6.4ca5b53ef9037562a235.js:1
```

**Comment by spencerthayer** [comment]
Same issue with 2.1.0.
